# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shrinkr < Formula
  desc "Fast image compression & format conversion CLI tool"
  homepage "https://github.com/idrewlong/shrinkr_cli"
  version "1.0.0"
  license "MIT"

  depends_on "vips"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/idrewlong/shrinkr_cli/releases/download/v1.0.0/shrinkr_1.0.0_darwin_arm64.tar.gz"
    sha256 "877b49c60a11a6c4158a0c2340bcfa73e662174e5d15933847826c69879181f9"

    define_method(:install) do
      bin.install "shrinkr"
    end
  end

  test do
    system "#{bin}/shrinkr", "--help"
  end
end
