# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morphr < Formula
  desc "Fast RAW image converter CLI — CR2, NEF, ARW, DNG to JPEG, PNG, TIFF, WebP, AVIF"
  homepage "https://github.com/idrewlong/morphr"
  version "1.0.0"
  license "MIT"

  depends_on "dcraw"
  depends_on "exiftool"
  depends_on "libavif"
  depends_on "webp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/idrewlong/morphr/releases/download/v1.0.0/morphr_1.0.0_darwin_amd64.tar.gz"
      sha256 "531ee2058a96feec2e942a26c089fe78ba19e21f923920738d4604fe7eb953d8"

      define_method(:install) do
        bin.install "morphr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/idrewlong/morphr/releases/download/v1.0.0/morphr_1.0.0_darwin_arm64.tar.gz"
      sha256 "f16d2a6004eca18a9c1ddfca5c9952fcec0f163d5660c393432347093b6779a9"

      define_method(:install) do
        bin.install "morphr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/idrewlong/morphr/releases/download/v1.0.0/morphr_1.0.0_linux_amd64.tar.gz"
      sha256 "2fdc636ebabd59ebb23e96002494ca1c7b355d252289d987dc0a1b7a68e443c6"
      define_method(:install) do
        bin.install "morphr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/idrewlong/morphr/releases/download/v1.0.0/morphr_1.0.0_linux_arm64.tar.gz"
      sha256 "f8ee02e8c9b8bd5fa79ec3616e2de280b25352623de1b80743ae925c8faa62d2"
      define_method(:install) do
        bin.install "morphr"
      end
    end
  end

  test do
    system "#{bin}/morphr", "--help"
  end
end
