# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morphr < Formula
  desc "Fast RAW image converter CLI — CR2, NEF, ARW, DNG to JPEG, PNG, TIFF, WebP, AVIF"
  homepage "https://github.com/idrewlong/morphr"
  version "1.0.0"
  license "MIT"

  depends_on "dcraw"
  depends_on "exiftool"
  depends_on "libavif"
  depends_on "webp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/idrewlong/morphr/releases/download/v1.0.0/morphr_1.0.0_darwin_amd64.tar.gz"
      sha256 "933e613b8840cd2ec4c1540db1d03eba7b00e6ad49a495b9be229cc36aafa702"

      define_method(:install) do
        bin.install "morphr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/idrewlong/morphr/releases/download/v1.0.0/morphr_1.0.0_darwin_arm64.tar.gz"
      sha256 "0c9a5265b4434d66df07c2cfa82ef38d1476a65c884f64a86a283d622414490e"

      define_method(:install) do
        bin.install "morphr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/idrewlong/morphr/releases/download/v1.0.0/morphr_1.0.0_linux_amd64.tar.gz"
      sha256 "6347e116002b00bdb3a16c5dedf9aa8db00e6888155756e8a543760f671d9fed"
      define_method(:install) do
        bin.install "morphr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/idrewlong/morphr/releases/download/v1.0.0/morphr_1.0.0_linux_arm64.tar.gz"
      sha256 "7a7a3d68e1082138a5823d4f255f2b2c57a085f16011bd98e36d885c6e22ddf8"
      define_method(:install) do
        bin.install "morphr"
      end
    end
  end

  test do
    system "#{bin}/morphr", "--help"
  end
end
