# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morphr < Formula
  desc "Fast RAW image converter CLI — CR2, NEF, ARW, DNG to JPEG, PNG, TIFF, WebP, AVIF"
  homepage "https://github.com/idrewlong/morphr"
  version "1.0.0"
  license "MIT"

  depends_on "dcraw"
  depends_on "exiftool"
  depends_on "libavif"
  depends_on "webp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/idrewlong/morphr/releases/download/v1.0.0/morphr_1.0.0_darwin_amd64.tar.gz"
      sha256 "a3280711a3329e9ebcac9e0f8d99561e195a7c0975c1a7e20426ca2a2464729b"

      define_method(:install) do
        bin.install "morphr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/idrewlong/morphr/releases/download/v1.0.0/morphr_1.0.0_darwin_arm64.tar.gz"
      sha256 "4bb81635ca6e138ebbc14389d437f6776e2552144fc3936b3135ed2f13d605df"

      define_method(:install) do
        bin.install "morphr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/idrewlong/morphr/releases/download/v1.0.0/morphr_1.0.0_linux_amd64.tar.gz"
      sha256 "2fcb62d3dc19961b617db2af50ed5f9f8c5cdf2d39b10389125affb4cfaf0884"
      define_method(:install) do
        bin.install "morphr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/idrewlong/morphr/releases/download/v1.0.0/morphr_1.0.0_linux_arm64.tar.gz"
      sha256 "c00f4dc2de4b6856882b446a5c2196963510a82ed980d7f9cf60afc1d8442319"
      define_method(:install) do
        bin.install "morphr"
      end
    end
  end

  test do
    system "#{bin}/morphr", "--help"
  end
end
